# Site settings
title: A Journey into Data Science
url: "https://ryanhomer.github.io"
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
timezone: America/Vancouver
lang: en_CA
webmaster_verifications:
  google: "kbvSiBpivxTgHlkq_-j-2RI_o1KIvAgacVxnB5ukwOQ"
description: >
  A blog of a professional Software Developer making his way into the realm of Data Science.

# Your information
author: Ryan Homer
avatar:
  1x: "https://gravatar.com/avatar/30e45bcbe425836a2c970e896ffe55d0?s=135"
  2x: "https://gravatar.com/avatar/30e45bcbe425836a2c970e896ffe55d0?s=270"
tagline: Frontend Software Developer<br/>Aspiring Data Scientist
twitter_username: techrah
github_username:  ryanhomer
linkedin_username: ryanhomer
stackoverflow_userid: 305383
profile_links:
  # LinkedIn: "https://www.linkedin.com/in/ryanhomer/"
  # You can add more profile links above, or edit _includes/sidebar.html

# Comment Service (Disqus or 多说)
disqus_shortname: https-ryanhomer-github-io
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: "\n\n"

# List of links in the navigation bar
navbar-links:
  Reference:
    - Machine Learning Algorithms: /data-science/machine-learning-algorithms/
    - LaTeX for Data Science: /data-science/latex-for-data-science/
  Education: /education/
  Categories: /categories/
  About: /about/

permalink: /posts/:title
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

twitter:
  username: techrah
  card: summary

# Exclude from processing.
exclude:
  - build
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
